modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="anomalous_albums"
version="1.0.0"
displayName="Anomalous Albums"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Zemabri"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.anomalous_albums]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration